### ISSUE TITLE
Attention scale

### ISSUE THREAD

**Issue by shkarupa-alex** [Visual-Attention-Network/VAN-Segmentation#2]
Usually attention values are in range [0; 1]. E.g. Softmax in self-attention, sigmoid in other attention types.
But in your implementation i did't see such scale preserving.
If it is correct?

**Comment by MenghaoGuo** [comment]
Yes, you are right. The LKA is not in range [0; 1].

**Comment by intervolga-school** [comment]
Have you made some experiments about it?

**Comment by MenghaoGuo** [comment]
No, we'll try it if we have time and GPUs.
