### ISSUE TITLE
AlignResize

### ISSUE THREAD

**Issue by xiaoyudanaa** [Visual-Attention-Network/VAN-Segmentation#5]
您好，看到您的文章我受到了很大的启发，但我目前代码能力不太好。有个问题想问您。就是我用的数据集的图像大小是192*640，我不知道在train.py中如何通过AlignResize这个函数将图像改成224-224的尺寸。非常期待您的回复，万分感谢

**Comment by LGYoung** [comment]
如果您想要customize数据集，请参考mmseg官方repo
更多关于AlignResize的细节请参考[这里](https://github.com/open-mmlab/mmsegmentation/blob/6c3e63e48b8f94a64ac5b1d88cab6fca005ae269/mmseg/datasets/pipelines/test_time_aug.py#L11)
