### ISSUE TITLE
missing upernet_van.py

### ISSUE THREAD

**Issue by sniklaus** [Visual-Attention-Network/VAN-Segmentation#6]
Huge thanks for sharing your work, this is great! Just a quick question, there is a reference to `upernet_van.py` as shown below but I am unfortunately unable to find it. Would you be so kind to share it as well? Thanks!

https://github.com/Visual-Attention-Network/VAN-Segmentation/blob/0ece089912fe40d25ac17c7c6c892bb35da92728/configs/upernet/VAN/upernet_van_large_512x512_160k_ade20k.py#L2

**Comment by LGYoung** [comment]
Sorry!
We update the path in configs.
