### ISSUE TITLE
Weights for VAN + UperNet

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Visual-Attention-Network/VAN-Segmentation#8]
Thanks for the amazing contribution. Are they any plans to share the weights of VAN + UperNet?

**Comment by MenghaoGuo** [comment]
Yes, we will share it soon.

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks!

**Comment by FrancescoSaverioZuppichini** [comment]
updates on this?

**Comment by Gsunshine** [comment]
Hi! You can use VAN + Light Ham for segmentation, offering SOTA Pareto curves (Params/FLOPs-mIoU curves). Code and checkpoints are available now.
